import { Button } from "std-widgets.slint";

//'sshfs michael@192.168.1.197:/home/michael/ ~/Dev -o volname=DEV'

export component ConfirmDialog inherits Window {
    in-out property<string> title: "";
    in-out property<string> message: "";
    in-out property on_ok;
    in-out property on_cancel;

    VerticalBox {
        Text {
                text: "hello world";
                color: green;
            }
    }
}
